apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: f3zjnue8s-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:7a0830b53ff1502c1ae598cc3436c959fa273224@sha256:cda97d26970e6b58e16d177c08fbc340f7ec84ca1e2130aeb1a294ef9828bbcd
          name: container-image
